apiVersion: v1
kind: Service

metadata:
  name: employee-service
  namespace: employee-management

spec:
  selector:
    app: employee-api

  ports:
    - port: 8000
      targetPort: 8000

  type: NodePort