apiVersion: v1
kind: Secret

metadata:
  name: employee-secret
  namespace: employee-management

type: Opaue

stringData:
  DB_PASSWORD: admin123
  WEATHER_API_KEY: fd0b19b4bd14cf9d71619305d40d2765